### ISSUE TITLE
请问你们的论文发表了吗？

### ISSUE THREAD

**Issue by linh47** [TsingZ0/TLSAN#1]
=v= google没搜到诶，能否请您指个路

**Comment by linh47** [comment]
运行代码的时候发现了小错误，您看看是否需要更新一下。
tf的variable_scope ，名字不能有短横线，model.py里面这几个地方会报错：
ValueError: 'long-term layer' is not a valid scope name

with tf.variable_scope("long-term"):
with tf.variable_scope('long-term layer'):
with tf.variable_scope("short-term"):
with tf.variable_scope("short-term layer"):

我改成longTerm之类的名字了，中间有空格也不行。

我今天刚好在跑ATRank的代码，看到这个文件结构真的好熟悉，哈哈，谢谢你们的代码~~~学习了

**Comment by TsingZ0** [comment]
抱歉，看到消息晚了。这里确实是在修改便于理解的名称的时候，疏忽了。非常感谢！这个结构确实非常有利于搭建神经网络，欢迎一起学习交流！论文正在投稿中:）
