### ISSUE TITLE
KeyError: 'k'

### ISSUE THREAD

**Issue by Leathertiger** [TsingZ0/TLSAN#3]
# user position preference
        usert_emb = tf.get_variable(
            "usert_emb", 
            [self.config['user_count'], self.config['k']], 
            initializer=tf.constant_initializer(-1.0))

Hello, I ran the code but It didn't success.The error is: KeyError: 'k'.

**Comment by TsingZ0** [comment]
Please replace 'k' with 'SL', which is updated in [model.py](https://github.com/TsingZ0/TLSAN/blob/master/TLSAN/model.py).
