### ISSUE TITLE
paper link

### ISSUE THREAD

**Issue by youngzw** [TsingZ0/TLSAN#4]
hi, TsingZ0.
Is there a paper link about your nice work "TLSAN: Time-aware Long- and Short-term Attention Network for Next-item Recommendation",  I tried to search it by google scholar/arxiv/web of science,  but failed to get the paper info :).

**Comment by TsingZ0** [comment]
Sorry for the late reply. You can now search the paper on Google Scholar, or you can just visit [TLSAN: Time-aware Long- and Short-term Attention Network for Next-item Recommendation](https://www.sciencedirect.com/science/article/abs/pii/S0925231221002605). The full-text is also available here: https://www.researchgate.net/publication/349912702_TLSAN_Time-aware_Long-_and_Short-term_Attention_Network_for_Next-item_Recommendation. 

Besides, I have added the experimental results in the README :-)
