### ISSUE TITLE
可以多类型建模吗

### ISSUE THREAD

**Issue by aceyw** [TsingZ0/TLSAN#5]
您好，看到git代码和readme，是一次训练、测试一种类别的。
可以把不同的类别（书、电子产品、衣服、等）数据一起用来训练模型吗？

**Comment by TsingZ0** [comment]
您好，为了与现有方法进行更好的对比，我们采用了将Amazon的官方数据集预处理后进行实验，并未对这几个数据集进行融合。不过，我们的模型是可以对不同类别的数据进行学习的，没有这方面限制。

**Comment by aceyw** [comment]
了解了，谢谢~
